moves_first = ['accelerock',
'ally switch',
'aqua jet',
'baby-doll eyes',
'baneful bunker',
'bide',
'bullet punch',
'crafty shield',
'detect',
'endure',
'extreme speed',
'fake out',
'feint',
'first impression',
'follow me',
'helping hand',
'ice shard',
'ion deluge',
"king's shield",
'mach punch',
'magic coat',
'obstruct',
'powder',
'protect',
'quick attack',
'quick guard',
'rage powder',
'shadow sneak',
'snatch',
'spiky shield',
'spotlight',
'sucker punch',
'vacuum wave',
'water shuriken',
'wide guard',
'zippy zap']

charge_moves_invulnerable = ['bounce',
'dig',
'dive',
'fly',
'phantom force',
'shadow force',
'sky drop']

charge_moves_vulnerable = ['freeze shock',
'geomancy',
'ice burn',
'razor wind',
'skull bash',
'sky attack',
'sky drop',
'solar beam',
'solar blade']

modify_target_stats = ['aurora beam',
'baby-doll eyes',
'breaking swipe',
'charm',
'feather dance',
'growl',
"king's shield",
'lunge',
'memento',
'noble roar',
'parting shot',
'play nice',
'play rough',
'secret power',
'strength sap',
'tearful look',
'tickle',
'trop kick',
'venom drench',
'acid',
'crunch',
'crush claw',
'fire lash',
'grav apple',
'iron tail',
'leer',
'liquidation',
'max phantasm',
'obstruct',
'octolock',
'razor shell',
'rock smash',
'screech',
'secret power',
'shadow bone',
'shadow down',
'tail whip',
'thunderous kick',
'tickle',
'captivate',
'confide',
'eerie impulse',
'memento',
'mist ball',
'moonblast',
'mystical fire',
'noble roar',
'parting shot',
'secret power',
'snarl',
'spirit break',
'struggle bug',
'tearful look',
'venom drench',
'acid',
'acid spray',
'apple acid',
'bug buzz',
'crunch',
'earth power',
'energy ball',
'fake tears',
'flash cannon',
'focus blast',
'luster purge',
'max darkness',
'metal sound',
'octolock'
'psychic',
'seed flare',
'shadow ball',
'bubble',
'bubble beam',
'bulldoze',
'constrict',
'cotton spore',
'drum beating',
'electroweb',
'g-max foam burst',
'glaciate',
'icy wind',
'low sweep',
'max strike',
'mud shot',
'rock tomb',
'scary face',
'secret power',
'sticky web',
'string shot',
'tar shot',
'toxic thread',
'venom drench',
'acupressure',
'decorate',
'gear up',
'rototiller',
'swagger',
'acupressure',
'flower shield',
'magnetic flux',
'acupressure',
'decorate',
'flatter',
'gear up',
'rototiller',
'acupressure',
'aromatic mist',
'magnetic flux',
'acupressure']